Add about myself section
enoqueJonas/Portfolio pull request #6
Opened 2022-09-23 20:36 UTC by enoqueJonas

Added new:
- Projects/ Cards section that will display the projects on the website
- About me section

2022-09-23 22:15 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @enoqueJonas , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 22:15 UTC, bobb-Rob commented on index.html
> +                <div class="works-item-info-block">
- [ ] [REQUIRED] You are expected to use `display: grid` to align this section `<section id="works">`. Kindly implement this. See image below for a reminder 👇 

![image](https://user-images.githubusercontent.com/84156714/192062088-aa4dd5e7-8be3-45eb-8bc6-9e9c31a60839.png)

2022-09-23 22:15 UTC, bobb-Rob commented on index.html
> +                    <li>
- [ ] Please ensure your whole project uses the correct font family defined in the Figma design template. Kindly add the various font family to the necessary elements according to the Figma design.

2022-09-23 22:15 UTC, bobb-Rob commented on index.html
> +                        <img src="img/Disabled.png" alt="" class="languages-frame-dropdown">
- [ ] [REQUIRED] Please consider making the technology categories ("Languages", "Frameworks" and "Skills") structured with a `ul`, each of them in a `li` and technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`. Essentially this will be a two layer `ul` nesting.

2022-09-23 22:15 UTC, bobb-Rob commented on index.html
> +                    </p>
- [ ] [REQUIRED] Please use an `anchor tag`  instead of `span`. This is expected to be a link to a path. 

`<span>LET'S CONNECT</span>`

2022-09-24 06:58 UTC, aimalamiri requested changes
Hi @enoqueJonas, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191356050-93e2eb80-7c05-4749-92f7-8925a1fa9386.gif)


 ## Highlights

- The header section is designed very well and look fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 06:58 UTC, aimalamiri commented on index.html
> +                        </button>
[Optional] To make your web page look somewhat interactive, it's recommended to add basic button interactions like hover, pressed, etc. 

![image](https://user-images.githubusercontent.com/34779928/192084447-51f9e626-5b23-409a-aa19-dbb30b91ac33.png)

2022-09-24 06:58 UTC, aimalamiri commented on index.html
> +            <div class="works-item works-item-2">
[Optional] As the previous reviewer mentioned it's important to stick with the Figma design as much as possible. So please make sure to put some space between the work cards.

![image](https://user-images.githubusercontent.com/34779928/192084157-76157b18-dbb3-4388-9a97-92fe8deb892b.png)

2022-09-24 06:58 UTC, aimalamiri commented on index.html
> +                        <li>
The social media icons are coming to the right side of the button, please make sure to fix it.

![image](https://user-images.githubusercontent.com/34779928/192084599-7c0cd6a2-c38d-4ce5-8219-e1b508b64861.png)

2022-09-24 09:10 UTC, Kamba56 requested changes
Hi @enoqueJonas, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Great use of Github flow
- [ ] All linters passed

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 09:10 UTC, Kamba56 commented on index.html
> +        <section id="works">
- [ ] As requested by the first reviewer, kindly use CSS grid to lay out the contents of this section. This is demanded by the project's requirements. Please use the `display: grid;` CSS property and use `grid-template-columns:` and `grid-template-rows:` to arrange the grid items.

2022-09-24 09:10 UTC, Kamba56 commented on index.html
>                  </li>
- [Optional] Please remove the spacing between the list of technologies to match the figma template. You are expected to stick to design as much as possible.
### Your design
![12](https://user-images.githubusercontent.com/94551484/192089902-accbd4d0-c3eb-43af-aa5e-e9e5f62d151a.png)
### Figma template
![f12](https://user-images.githubusercontent.com/94551484/192089905-8c86d452-8f87-4dc9-8f93-d72238a82d8a.png)

2022-09-24 09:10 UTC, Kamba56 commented on index.html
> +                <button id="btn-get-resume"><span> Get my resume</span></button>
- [Optional] Please add a hover and pressed state to your buttons according to the design template. You can use the `:hover` and `:active` pseudo-classes to implement this states in your css.
![192084447-51f9e626-5b23-409a-aa19-dbb30b91ac33](https://user-images.githubusercontent.com/94551484/192089982-10df0c78-cd18-43c5-b7ee-e87794d9977b.png)

2022-09-24 09:10 UTC, Kamba56 commented on index.html
> +                    <li>
- [Optional] Consider using an indentation of two spaces in all your documents for readability. This is a convention and also [best practice.](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-09-24 09:11 UTC, Kamba56 requested changes
Hi @enoqueJonas, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Great use of Github flow
- [ ] All linters passed

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 11:31 UTC, awais-amjed approved these changes
# STATUS: APPROVED 🥳

Hi @enoqueJonas , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations on implementing the required changes! 🎉👏🥇✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] No Linter issues ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 12:29 UTC, merged